##GET ALL CATEGORY
GET http://localhost:3000/api/categories
Accept: application/json

###CREATE NEW CATEGORY
POST http://localhost:3000/api/categories
Accept: application/json
Content-Type: application/json

{
"name": "PC GAMING NVIDIA 750TX"
}


###DELETE NEW CATEGORY
DELETE http://localhost:3000/api/categories/1
Accept: application/json
