##GET ALL CATEGORY
GET http://localhost:3000/api/categories
Accept: application/json

###CREATE NEW CATEGORY
POST http://localhost:3000/api/categories
Accept: application/json
Content-Type: application/json

{
  "name": ""
}

### GET CATEGORY BY Id
GET http://Localhost:3000/api/categories/124
Accept: application/json

###DELETE NEW CATEGORY
DELETE http://localhost:3000/api/categories/2
Accept: application/json
